skylines-project/skylines

skylines/frontend/templates/flights/details-table.jinja
skylines/frontend/templates/flights/view.jinja
skylines/frontend/templates/flights/wingman-table.jinja
skylines/frontend/templates/users/users-table.jinja
skylines/frontend/templates/users/view.jinja

This should fix the ssl warnings we get on the flight view pages.

Added https urls for schema, facebook and twitter

---

skylines/commands/aircraft.py
skylines/model/aircraft_model.py

I was was looking for some posibilities to manipulate with aircraft models. I have added few  helpful commands.
./manage.py aircraft list
./manage.py aircraft delete_model id
./manage.py aircraft kind_enum

manipulation with aircrafts models

---

skylines/frontend/translations/sl/LC_MESSAGES/messages.po

babel compile passes without errors.

Slovenian translation

---

skylines/frontend/translations/sl/LC_MESSAGES/messages.po

- change in line 176 %(welt2000)s is causing an error
- uncomment other translations

Slovenian translation error fix

---

skylines/frontend/views/notifications.py

1: Logout while reading notifications -> 401 => Redirect to "index"
2: Direct access as anonymous -> 401 => Request for login

Avoiding 401 on site "Notifications"

---

INSTALL.md
skylines/frontend/forms/pilot.py
skylines/frontend/translations/cs/LC_MESSAGES/messages.po
skylines/frontend/translations/de/LC_MESSAGES/messages.po
skylines/frontend/translations/en/LC_MESSAGES/messages.po
skylines/frontend/translations/es/LC_MESSAGES/messages.po
skylines/frontend/translations/fi/LC_MESSAGES/messages.po
skylines/frontend/translations/fr/LC_MESSAGES/messages.po
skylines/frontend/translations/hu/LC_MESSAGES/messages.po
skylines/frontend/translations/ja/LC_MESSAGES/messages.po
skylines/frontend/translations/messages.pot
skylines/frontend/translations/nb/LC_MESSAGES/messages.po
skylines/frontend/translations/nl/LC_MESSAGES/messages.po
skylines/frontend/translations/pl/LC_MESSAGES/messages.po
skylines/frontend/translations/pt/LC_MESSAGES/messages.po
skylines/frontend/translations/ro/LC_MESSAGES/messages.po
skylines/frontend/translations/ru/LC_MESSAGES/messages.po
skylines/frontend/translations/sk/LC_MESSAGES/messages.po
skylines/frontend/translations/sl/LC_MESSAGES/messages.po
skylines/frontend/translations/sv/LC_MESSAGES/messages.po
skylines/frontend/translations/zh_TW/LC_MESSAGES/messages.po
skylines/frontend/views/login.py
skylines/model/user.py

this PR continues #380 
/cc @clementallen

Spelling fixes

---

setup.py
skylines/api/airports.py
skylines/api/airspace.py
skylines/api/schemas.py
skylines/api/waves.py
skylines/app.py
skylines/frontend/static/js/slMapClickHandler.js
tests/api/schemas_airport_test.py
tests/api/schemas_airspace_test.py
tests/api/schemas_wave_test.py
tests/conftest.py
tests/data/airports.py
tests/data/airspace.py

see http://marshmallow.readthedocs.org/

Use Marshmallow lib for API response serializing

---

skylines/api/views/__init__.py
skylines/api/views/search.py
tests/api/views/search_test.py

Example output for `GET /search?q=aac`:
```json
[
{
"icao": "EDKA",
"frequency": "122.875",
"type": "airport",
"id": 1,
"name": "Aachen Merzbruck"
},
{
"website": null,
"type": "club",
"id": 1073,
"name": "Luftsportverein Aachen e.V"
},
{
"website": null,
"type": "club",
"id": 444,
"name": "Flugwissenschaftliche Vereinigung Aachen (1920) e.V."
},
{
"website": null,
"type": "club",
"id": 867,
"name": "LVA Aachen"
},
{
"website": null,
"type": "club",
"id": 868,
"name": "sfz aachen"
},
{
"website": "http://www.lv-aachen.de/",
"type": "club",
"id": 15,
"name": "LV Aachen"
},
{
"website": null,
"type": "club",
"id": 319,
"name": "SFZ Aachen"
},
{
"website": null,
"type": "club",
"id": 531,
"name": "DJK Aachen"
},
{
"website": null,
"type": "club",
"id": 998,
"name": "FAG Aachen e.V."
},
{ …
```

API: Add "/search" route

---

skylines/frontend/assets/bundles.py
skylines/frontend/static/css/bootstrap-theme-skylines.css
skylines/frontend/templates/flights/flights-table.jinja
skylines/frontend/templates/flights/list.jinja
skylines/frontend/templates/flights/map.jinja

This PR fixes:
- Broken Asset URLs
- Problematic array iteration in the flight map view
- Unnecessarily complex JS for showing/hiding the pin stars in the flight list

Small Fixes

---

ember/translations/de.yaml
ember/translations/en.yaml
ember/translations/es.yaml
ember/translations/ru.yaml

Pull request created by LingoHub based on branch master

LingoHub based on master

---

ember/app/templates/components/user-details.hbs

Fixes issue #438 - Followers / following pages not found

user-details: Fix "followers / following" link typo

---

Vagrantfile
skylines/model/user.py

First commit adds port forwarding for tracking server.
The second commit removes only an obsolete comment and is totally unrelated.

Add port forwarding for tracking server

---

ember/app/components/contest-layer.js
ember/app/components/flight-path-layer.js
ember/app/components/layer-switcher.js
ember/app/components/pin-button.js
ember/app/components/pin-star.js
ember/app/components/takeoffs-layer.js
ember/app/components/tracking-tables.js
ember/app/components/user-page.js
ember/app/helpers/contains.js
ember/app/helpers/includes.js
ember/app/services/pinned-flights.js
ember/app/templates/components/flights-table-row.hbs
ember/package.json

see http://emberjs.com/deprecations/v2.x/#toc_enumerable-contains

Minor bugfixes and deprecation warning removals

---

tests/api/views/search_test.py

Improved search_test in the way, that the search result's order doesn't matter.

improved search_test

---

skylines/frontend/templates/base.jinja
skylines/frontend/views/__init__.py

we got an open-source charity account now 🎉

Use TrackJS for client-side error reporting

---

skylines/lib/waypoints/welt2000.py

Fixes https://github.com/skylines-project/skylines/issues/442

Change WELT2000 import path to point to skylines' fork

---

tests/frontend/views/flight_test.py

This PR tries to refactor the tests added in #446 to make them more readable, concise and reusable.
/cc @Harry-R

Flight test code cleanup

---

ember/app/templates/components/flight-details-table.hbs

components/flight-details-table: Use UTC timezone for date display

---

ember/bower.json
ember/ember-cli-build.js
skylines/frontend/assets/bundles.py

This makes it easier to work on SkyLines while being offline... or in an airplane...
Make sure to run `bower install` in the `ember` folder before attempting to run `./manage.py assets build` from now on!

Replace HTTP links by Bower dependencies

---

ember/app/components/change-pilot-form.js
ember/app/components/pilot-select.js
ember/app/components/upload-result-form.js
ember/app/computed/is-none.js
ember/app/validators/not-equal.js

Changing the pilots of a flight with only named pilots without IDs wasn't working properly.

Fix pilot select component

---

Vagrantfile
ember/app/components/pilot-select.js
ember/app/routes/application.js
fabfile.py
uwsgi/mapproxy.ini
uwsgi/mapserver.ini
uwsgi/skylines-api.ini
uwsgi/skylines.ini

see commit messages for details

Several minor bugfixes

---

skylines/schemas/schemas.py
skylines/schemas/validate.py
tests/schemas/schemas/test_club.py

`website` did not accept empty strings previously 😕

Fix ClubSchema class

---

ember/app/components/change-aircraft-form.js
ember/app/components/change-pilot-form.js
ember/app/components/club-edit-form.js
ember/app/components/recover-step1-form.js
ember/app/components/recover-step2-form.js
ember/app/components/register-form.js
ember/app/components/settings-panels/choose-club.js
ember/app/components/settings-panels/password.js
ember/app/components/settings-panels/profile.js
ember/app/components/settings-panels/register-club.js
ember/app/components/settings-panels/tracking-key.js
ember/app/components/settings-panels/tracking.js
ember/app/components/upload-results-form.js
ember/app/controllers/notifications.js
ember/app/routes/notifications.js
ember/app/templates/components/change-aircraft-form.hbs
ember/app/templates/components/change-pilot-form.hbs
ember/app/templates/components/club-edit-form.hbs
ember/app/templates/components/recover-step1-form.hbs
ember/app/templates/components/recover-step2-form.hbs
ember/app/templates/components/register-form.hbs
ember/app/templates/components/settings-panels/choose-club.hbs
ember/app/templates/components/settings-panels/password.hbs
ember/app/templates/components/settings-panels/profile.hbs
ember/app/templates/components/settings-panels/register-club.hbs
ember/app/templates/components/settings-panels/tracking-key.hbs
ember/app/templates/components/settings-panels/tracking.hbs
ember/app/templates/components/upload-results-form.hbs
ember/app/templates/notifications.hbs
ember/package.json

see http://ember-concurrency.com/

Use "ember-concurrency" for async AJAX result handling

---

ember/app/components/contest-layer.js
ember/app/components/datetime-picker.js
ember/app/components/flight-path-layer.js
ember/app/routes/search.js
ember/app/styles/_modals.scss
ember/app/styles/app.scss
ember/config/ember-intl.js
ember/ember-cli-build.js
ember/package.json
tests/frontend/views/index_test.py

This PR contains a few minor bugfixes again.
Resolves #444

Minor bugfixes

---

ember/app/components/nav-bar-search-form.js
ember/app/controllers/application.js
ember/app/templates/application.hbs
ember/app/templates/components/flight-details-table.hbs
ember/app/templates/components/nav-bar-search-form.hbs
ember/app/templates/components/nav-bar.hbs
ember/app/templates/components/timeline-events/club-join.hbs
ember/app/templates/components/timeline-events/flight-comment.hbs
ember/app/templates/components/timeline-events/flight-upload.hbs
ember/app/templates/components/timeline-events/follower.hbs
ember/app/templates/components/timeline-events/new-user.hbs
ember/package.json

This PR resolves two of the remaining issues mentioned in #483.

Client-side routing

---

ember/app/authenticators/cookie.js
ember/app/components/login-form.js
ember/app/components/nav-bar-menu-right.js
ember/app/components/nav-bar-user-menu.js
ember/app/routes/application.js
ember/app/routes/flight-upload.js
ember/app/routes/login.js
ember/app/routes/notifications.js
ember/app/routes/settings.js
ember/app/services/account.js
ember/app/templates/components/nav-bar-menu-right.hbs
ember/package.json
skylines/frontend/views/login.py
skylines/frontend/views/upload.py

see http://ember-simple-auth.com/

Use "ember-simple-auth" for client-side authentication

---

skylines/lib/dbutil.py

lib/dbutil: Fix "KeyError: 'babel'" exception

---

ember/app/routes/flights/pinned.js
ember/app/utils/map-click-handler.js
ember/config/environment.js
ember/ember-cli-build.js
skylines/frontend/views/flight.py
skylines/frontend/views/flights.py
skylines/frontend/views/login.py
skylines/frontend/views/ranking.py
skylines/frontend/views/settings.py
skylines/frontend/views/users.py

This PR removes and simplifies a few of the server-side routes.

Cleanup server-side routes

---

ember/app/controllers/index.js
ember/app/templates/club/pilots.hbs
ember/app/templates/index.hbs
ember/app/templates/ranking/pilots.hbs

This PR converts a few more links to in-app links by using the `href-to` helper.

Use {{href-to}} in translated strings

---

ember/app/components/upload-flight-form.js
ember/app/routes/flight-upload.js
ember/app/templates/components/upload-flight-form.hbs
ember/app/templates/flight-upload.hbs
skylines/frontend/views/upload.py

The `<iframe>` hack was introduced for better browser compatibility, but it seems that it works worse than just using `FormData` instead.

Kill <iframe> hack for flight uploads

---

skylines/frontend/views/flight.py

Fixes an issue introduced by #507 ... 🤔

views/flight: Fix broken "g.current_user" reference

---

ember/app/components/aircraft-model-select.js
ember/app/templates/flight/change-aircraft.hbs

Fix aircraft model selection

---

ember/app/templates/components/pin-button.hbs
ember/app/templates/components/settings-panels/tracking-key.hbs
ember/translations/en.yaml
ember/translations/fr.yaml

Add missing translations for some templates

---

ember/app/templates/components/pin-button.hbs
ember/app/templates/components/settings-panels/tracking-key.hbs
ember/app/templates/flights.hbs
ember/app/templates/notifications.hbs
ember/app/templates/ranking.hbs
ember/app/templates/search.hbs
ember/app/templates/timeline.hbs
ember/app/templates/tracking/index_loading.hbs
ember/translations/en.yaml
ember/translations/fr.yaml

Add more missing translations in templates

---

ember/app/components/fix-table.js
ember/app/components/plane-label-overlay.js

Display plane registration if competition_id is null

---

ember/bower.json

Update "ember" to v2.10.0-beta.3

---

ember/app/router.js
ember/app/templates/page-not-found.hbs
ember/tests/acceptance/page-not-found-test.js
ember/translations/de.yaml
ember/translations/en.yaml

Add "page-not-found" route

---

ember/app/routes/flight/map-redirect.js
ember/app/routes/flights/index.js
ember/app/routes/ranking/index.js
ember/app/routes/settings/index.js
ember/app/routes/tracking/map-redirect.js
ember/package.json

Use "ember-redirect-to" for redirections

---

ember/app/initializers/intl.js

see https://github.com/andyearnshaw/Intl.js/issues/256#issuecomment-267705446

Ember: Disable broken Intl.js polyfill regex cache

---

ember/app/routes/flight/map-redirect.js
ember/app/routes/flights/index.js
ember/app/routes/ranking/index.js
ember/app/routes/settings/index.js
ember/app/routes/tracking/map-redirect.js
ember/package.json

Reverts skylines-project/skylines#583
see https://github.com/stefanpenner/ember-redirect-to/pull/2

Revert "Use "ember-redirect-to" for redirections"

---

ember/app/components/upload-result-form.js
ember/app/components/upload-results-form.js
ember/app/styles/_bootstrap-theme-skylines.scss
ember/app/templates/components/upload-result-form.hbs
ember/app/templates/components/upload-results-form.hbs
ember/app/utils/upload-result.js

- styling was broken (likely caused by https://github.com/skylines-project/skylines/pull/589)
- validations on result page for multiple uploads was broken (caused by https://github.com/emberjs/ember.js/issues/13948)

Fix flight upload page

---

ember/app/services/raven.js

services/raven: Fix ignoreError() edge case

---

ember/app/templates/components/flight-details-table.hbs

Fix broken IGC file download link

---

requirements.txt
skylines/database.py
skylines/model/flight_comment.py
skylines/model/trace.py
tests/api/oauth/access_to_secrets_test.py
tests/api/oauth/access_to_user_test.py
tests/api/views/aircraft_models_test.py
tests/api/views/flights/read_test.py
tests/api/views/flights/update_test.py
tests/conftest.py
tests/data/aircraft_models.py
tests/data/airports.py
tests/data/airspace.py
tests/data/clubs.py
tests/data/contest_legs.py
tests/data/flight_comments.py
tests/data/flight_phases.py
tests/data/flights.py
tests/data/igcs.py
tests/data/traces.py
tests/data/users.py

API Tests for "GET /flights/:id?extended"

---

ember/translations/nl.yaml

translations/nl: Fix broken plural rules

---

ember/app/components/date-picker.js

components/date-picker: Call off() only if "picker" is set

---

ember/app/components/aircraft-model-select.js
ember/app/components/base-barogram.js
ember/app/components/base-map.js
ember/app/components/circling-performance-table.js
ember/app/components/fix-table-row.js
ember/app/components/fix-table.js
ember/app/components/flight-barogram.js
ember/app/components/flight-details-table.js
ember/app/components/flight-list-row.js
ember/app/components/nav-bar-menu-right.js
ember/app/components/pin-button.js
ember/app/components/pin-star.js
ember/app/components/settings-panels/tracking.js
ember/app/components/validated-block.js
ember/app/components/wingman-row.js
ember/app/controllers/index.js
ember/package.json
ember/yarn.lock

see https://github.com/kellyselden/ember-awesome-macros
/cc @kellyselden

Use "ember-awesome-macros"

---

ember/ember-cli-build.js

Closes https://github.com/ember-cli/ember-cli/issues/6594

(build): Exclude Cesium from minification

---

.travis.yml

work around for https://github.com/yarnpkg/yarn/issues/3138

CI: Use Node 6 for frontend build and tests

---

ember/package.json
ember/yarn.lock

related to https://github.com/skylines-project/skylines/pull/631

Update "broccoli-uglify-sourcemap" to v1.5.2

---

ember/app/components/base-barogram.js

Resolves https://github.com/skylines-project/skylines/issues/635

components/base-barogram: Return empty array if "passive" is not set

---

.travis.yml

... which will hopefully fix our current CI issues

CI: Update "pip" before running

---

ember/package.json
ember/tests/acceptance/page-not-found-test.js
ember/tests/integration/components/flight-list-nav-test.js
ember/tests/integration/components/timeline-events/club-join-test.js
ember/tests/integration/components/timeline-events/flight-comment-test.js
ember/tests/integration/components/timeline-events/flight-upload-test.js
ember/tests/integration/components/timeline-events/follower-test.js
ember/tests/integration/components/timeline-events/new-user-test.js
ember/yarn.lock

Use "ember-native-dom-helpers" addon

---

ember/app/services/raven.js
ember/bower.json
ember/package.json
ember/yarn.lock

This should resolve https://sentry.io/skylines/frontend/issues/241119389/

Update Sentry plugin

---

ember/app/components/flight-list-row.js
ember/package.json
ember/yarn.lock

... by updating `ember-awesome-macros`. turns out https://github.com/kellyselden/ember-awesome-macros/issues/322 was causing this and a few other issues.
Resolves #649

Fix elevation display

---

ember/app/styles/_loading-indicator.scss
ember/app/styles/app.scss
ember/bower.json
ember/config/environment.js
ember/package.json
ember/yarn.lock

see https://github.com/HubSpot/PACE

Add loading indicator

---

INSTALL.vagrant.md

INSTALL.vagrant.md: Add section about the ember frontend

---

ember/app/templates/tracking/details.hbs

templates/tracking/details: Fix typo

---

ember/app/components/nav-bar-menu-right.js
ember/app/components/nav-bar-menu.js
ember/app/components/nav-bar.js
ember/app/controllers/application.js
ember/app/routes/application.js
ember/app/routes/flight-upload.js
ember/app/styles/_loading-indicator.scss
ember/app/styles/app.scss
ember/app/templates/application.hbs
ember/app/templates/components/nav-bar-link.hbs
ember/app/templates/components/nav-bar-menu-right.hbs
ember/app/templates/components/nav-bar-menu.hbs
ember/app/templates/components/nav-bar.hbs
ember/ember-cli-build.js
ember/package.json
ember/yarn.lock

This fixes the bug where on small screens the menu is not closing after clicking a link

Replace "ember-sass-bootstrap" with "ember-bootstrap"

---

ember/package.json
ember/yarn.lock

see https://github.com/kaliber5/ember-bootstrap/pull/434
thanks @simonihmig :)

Update "ember-bootstrap" to fix "nested transition" issue

---

ember/app/services/intl.js

related to https://github.com/ember-intl/ember-intl/issues/533

services/intl: Set <html> element "lang" attribute

---

ember/app/components/base-page.js
ember/app/styles/_bootstrap-theme-skylines.scss
ember/app/styles/_loading-indicator.scss
ember/app/styles/app.scss
ember/app/templates/components/base-page.hbs

This PR removes the unnecessary cluttered "content" box. It also adds a slight shadow to the navbar links and improves the styling of the "pace" loading indicator.

Improved styling

---

.travis.yml
ember/testem.js

see https://github.com/ember-cli/ember-cli/pull/7148

Use Chrome instead of PhantomJS for frontend test suite

---

.travis.yml

This should hopefully speed up the CI runs by a few seconds now that #682 unfortunately made them quite a bit slower 🤔

CI: Remove unnecessary "ember build" step

---

README.md

Resolves https://github.com/skylines-project/skylines/issues/620

README: Update "Contact and Contributing" section

---

ember/app/templates/components/flight-list-nav.hbs
ember/app/templates/components/flight-list-row.hbs
ember/app/templates/components/user-distance-flight.hbs
ember/app/templates/components/wingman-row.hbs
ember/app/templates/flight/index.hbs

Resolves https://github.com/skylines-project/skylines/issues/659

templates: Use UTC timezone to format dates and times where necessary

---

ember/app/styles/_ol3-sidebar.scss

Resolves #703 
similar to https://github.com/Turbo87/sidebar-v2/pull/127

Fix sidebar icon positioning

---

setup.py

Update `psycopg2` to v2.7.3.2

---

ember/package.json
ember/yarn.lock

This PR `ember-cli-mocha` and `ember-cli-eslint` and tests the changes in https://github.com/emberjs/ember-mocha/pull/173 and https://github.com/ember-cli/ember-cli-mocha/pull/229

Update `ember-cli-mocha` and `ember-cli-eslint`

---

ember/app/styles/bootstrap/_bootstrap-theme-skylines.scss
ember/app/styles/bootstrap/_navbar.scss

... by using `normal` font-weight everywhere instead of `300`
Resolves https://github.com/skylines-project/skylines/issues/711

Fix poor font rendering on Windows

---

ember/app/styles/_map.scss
ember/app/templates/components/flight-page.hbs
ember/app/templates/components/tracking-page.hbs

Resolves https://github.com/skylines-project/skylines/issues/652

Adjust scale line and attribution positioning

---

ember/app/templates/components/login-form.hbs
ember/app/templates/components/register-form.hbs
ember/app/templates/components/settings-panels/password.hbs
ember/app/templates/components/settings-panels/profile.hbs
ember/app/templates/components/settings-panels/register-club.hbs
ember/app/templates/components/validated-input.hbs

Closes https://github.com/skylines-project/skylines/issues/523

Add `autocomplete` attributes to `<input>` fields

---

ember/app/components/validated-block.js
ember/app/templates/components/change-aircraft-form.hbs
ember/app/templates/components/change-pilot-form.hbs
ember/app/templates/components/club-edit-form.hbs
ember/app/templates/components/login-form.hbs
ember/app/templates/components/recover-step1-form.hbs
ember/app/templates/components/recover-step2-form.hbs
ember/app/templates/components/register-form.hbs
ember/app/templates/components/settings-panels/password.hbs
ember/app/templates/components/settings-panels/profile.hbs
ember/app/templates/components/settings-panels/register-club.hbs
ember/app/templates/components/settings-panels/tracking.hbs
ember/app/templates/components/upload-flight-form.hbs
ember/app/templates/components/upload-result-form.hbs
ember/app/templates/components/validated-input.hbs

see https://github.com/offirgolan/ember-cp-validations/pull/358

Fix `targetObject` deprecation warning

---

setup.py

Update gevent package

---

ember/app/components/settings-panels/choose-club.js

This should fix #622.
`TypeError: Cannot read property 'id' of undefined`
occurred, when you choose "no club".

choose-club: fix #622

---

requirements.txt

Closes https://github.com/skylines-project/skylines/pull/730
/cc @Harry-R

Replace `fake-factory` dependency with `Faker`

---

migrations/versions/46434b0a4c10_split_user_name_into.py
skylines/commands/__init__.py
skylines/commands/aircraft.py
skylines/commands/flights/analysis.py
skylines/commands/flights/copy_flights.py
skylines/commands/flights/delete_flights.py
skylines/commands/flights/find_meetings.py
skylines/commands/flights/selector.py
skylines/commands/flights/update_flight_paths.py
skylines/commands/import_/airspace.py
skylines/commands/import_/mwp.py
skylines/commands/import_/srtm.py
skylines/commands/import_/welt2000.py
skylines/commands/search.py
skylines/commands/tracking/clear.py
skylines/commands/tracking/export.py
skylines/commands/tracking/generate.py
skylines/commands/tracking/generate_through_daemon.py
skylines/commands/tracking/server.py
skylines/commands/tracking/stats.py
skylines/commands/users/merge.py
skylines/tracking/server.py
tests/api/views/airports/read_test.py
tests/data/bootstrap.py
tests/test_flake8.py

This will eventually allow us to use Python 3

Use `print()` function instead of deprecated `print` keyword

---

ember/app/routes/application.js

... to improve GDPR compliance
Resolves #787

sentry: Share only user ID as user context

---

Pipfile
Pipfile.lock

see https://github.com/oauthlib/oauthlib/blob/master/CHANGELOG.rst and https://github.com/lepture/flask-oauthlib/blob/master/CHANGES.rst

Update `oauthlib` and `flask-oauthlib` dependencies

---

Pipfile
Pipfile.lock

see http://flask.pocoo.org/docs/1.0/changelog/

 Update `flask` to 1.0

---

migrations/versions/70a6f5e6f0e1_fix_refreshtoken_foreign_key.py
skylines/model/oauth.py
tests/model/test_oauth.py

Addresses part of https://github.com/skylines-project/skylines/issues/786#issuecomment-386877351

Fix `RefreshToken` foreign key

---

ember/app/components/settings-panels/delete-account.js
ember/app/services/notifications.js
ember/app/templates/components/nav-bar-menu-right.hbs
ember/app/templates/components/nav-bar-user-menu.hbs
ember/app/templates/components/nav-bar.hbs
ember/app/templates/components/settings-panels/delete-account.hbs
ember/app/templates/components/validated-block.hbs
ember/app/templates/components/validated-input.hbs
ember/app/templates/settings/profile.hbs
ember/tests/acceptance/settings/delete-account-test.js
ember/translations/de.yaml
ember/translations/en.yaml
skylines/api/views/__init__.py
skylines/api/views/account.py
skylines/api/views/users.py
skylines/model/user.py
tests/api/views/account/delete_test.py
tests/api/views/users/delete_test.py
tests/data/igcs.py
tests/model/test_user.py

Resolves the first half of https://github.com/skylines-project/skylines/issues/786

Add "Delete User" button

---

skylines/model/search.py
tests/api/views/search_test.py

Fix search including unicode characters

---

ember/app/index.html
ember/app/routes/application.js
ember/app/services/intl.js
ember/package.json
ember/yarn.lock

Resolves https://github.com/skylines-project/skylines/issues/773

Load Intl.js polyfill conditionally on app startup

---

INSTALL.mapserver.md
INSTALL.md

in the process of installation for development, i encounter some shortcomings in the documentation, which i try to rectify with this branch

Update installation notes

---

.editorconfig

... so that it also works for Markdown files at the top-level folder

Move `.editorconfig` file to the top-level folder

---

skylines/commands/tracking/__init__.py
skylines/commands/tracking/delete_old.py

related to https://github.com/skylines-project/skylines/issues/866
this command can then be automatically performed on the server using a cronjob or similar

Add `tracking delete-old` command

---

skylines/commands/import_/airspace.py

This was apparently broken by https://github.com/skylines-project/skylines/pull/821

commands/airspace: Remove broken `ReadingError` import

---

PRIVACY.md
ember/app/templates/components/base-page.hbs
ember/translations/de.yaml
ember/translations/en.yaml

[Rendered](https://github.com/Turbo87/skylines/blob/privacy-policy/PRIVACY.md)
related to https://github.com/skylines-project/skylines/issues/785

Add `PRIVACY.md` document

---

ember/yarn.lock

see https://github.com/MayhemYDG/iltorb/blob/master/CHANGELOG.md

Update `iltorb` subdependency

---

config/default.py
skylines/commands/users/__init__.py
skylines/commands/users/email.py

This was used earlier today to send out the GDPR notices.

Add `users email` command

---

ember/app/router.js
ember/app/templates/application.hbs
ember/ember-cli-build.js
ember/lib/.eslintrc.js
ember/lib/freestyle/app/controllers/freestyle.js
ember/lib/freestyle/app/routes/freestyle.js
ember/lib/freestyle/app/templates/components/usage/x-flag.hbs
ember/lib/freestyle/app/templates/freestyle.hbs
ember/lib/freestyle/index.js
ember/lib/freestyle/package.json
ember/package.json
ember/yarn.lock

see https://simplabs.com/blog/2018/01/24/ember-freestyle.html

Add `ember-freestyle` component playground

---

Vagrantfile

see commit messages
/cc @kerel-fs

Improve Vagrant environment

---

ember/bower.json
ember/ember-cli-build.js
ember/package.json
ember/vendor/shims/remarkable.js
ember/yarn.lock

see https://github.com/ef4/ember-auto-import

Use `ember-auto-import` to import `remarkable` via npm

---

skylines/api/views/clubs.py
skylines/api/views/flights.py
skylines/api/views/mapitems.py
skylines/api/views/notifications.py
skylines/api/views/timeline.py
skylines/api/views/users.py
skylines/commands/aircraft.py

Rename `list()` functions to `_list()` to prevent conflicts with builtin

---

skylines/lib/base36.py
skylines/lib/types.py
skylines/model/tracking.py

Extract `is_int()` helper function

---

skylines/commands/import_/dmst_index.py
skylines/lib/files.py
skylines/lib/igc.py
tests/model/test_user.py

`file()` no longer exists in Python 3

Use `open()` instead of `file()`

---

skylines/tracking/server.py

... to make it compatible with Python 3

tracking/server: Destructure `address` tuple parameter later

---

skylines/api/views/flights.py
skylines/lib/files.py
skylines/lib/igc.py
skylines/lib/string.py
skylines/lib/types.py
skylines/lib/xcsoar_/flightpath.py

Extract `is_string()` helper function

---

.travis.yml

This should slightly speed up the CI builds

CI: Split backend and frontend test into separate jobs

---

skylines/lib/basic_auth.py
tests/api/__init__.py
tests/api/oauth/access_to_secrets_test.py
tests/api/oauth/access_to_user_test.py
tests/lib/test_basic_auth.py

... to make unicode/bytes handling easier

basic_auth: Extract `encode()` helper function

---

skylines/api/oauth.py
skylines/database.py
skylines/lib/types.py
tests/api/oauth/access_to_secrets_test.py
tests/api/oauth/conftest.py

Make OAuth tests pass on Python 3

---

skylines/tracking/datetime.py
skylines/tracking/server.py
tests/tracking/test_datetime.py

Make tracking tests pass on Python 3

---

skylines/schemas/fields.py
tests/schemas/schemas/airspace_test.py

Make schema tests compatible with Python 3

---

skylines/api/views/about.py

This makes the corresponding tests pass on Python 3

api/about: Read files in binary mode to decode UTF8 later

---

skylines/model/search.py

model/search: Add Python 3 compatibility

---

skylines/lib/string.py
skylines/model/user.py
tests/model/test_user.py

This should resolve a few SQLAlchemy warnings

model/user: Fix return type of `_hash_password()` method

---

skylines/model/user.py

We don't use `flask-login` anymore...

model/user: Remove unused `flask-login` code

---

skylines/model/timezone.py
tests/model/test_timezone.py

model/timezone: Add tests and add Python 3 compat

---

skylines/lib/sql.py
tests/lib/test_sql.py

 lib/sql: Improve Python 3 compat 

---

skylines/lib/files.py
tests/lib/test_files.py

lib/files: Make `sanitise_filename()` compatible with Python 3 

---

skylines/lib/compat.py
skylines/lib/xcsoar_/flightpath.py

for Python 3 compat obviously 😉

lib/xcsoar: Use `xrange()` on Python 2 and `range()` on Python 3

---

skylines/api/views/timeline.py
tests/api/views/timeline/list_test.py

api/timeline: Improve Python 3 compatibility

---

skylines/api/views/upload.py

api/views/upload: Use `is_unicode()` function

---

.travis.yml

CI: Ensure that Python 3.4 test suite stays green too

---

skylines/api/views/flights.py
tests/api/views/flights/read_test.py
tests/voluptuous.py

... and add a basic smoke test for it

Fix `GET /api/flights/<id>/json` for Python 3

---

ember/yarn.lock

see https://github.com/atlassian/yarn-deduplicate

yarn: Deduplicate dependencies

---

.travis.yml
ember/.eslintignore
ember/.eslintrc.js
ember/.gitignore
ember/package.json
ember/yarn.lock

see https://github.com/ember-cli/rfcs/pull/121

Replace `ember-cli-eslint` with regular ESLint

---

ember/app/components/cesium-scene.js
ember/config/environment.js

Resolves https://github.com/skylines-project/skylines/issues/1221

Cesium: Fix terrain provider

---

ember/package.json
ember/yarn.lock

We don't use this for anything...

Remove unnecessary `ember-cli-app-version` dependency

---

ember/app/components/base-map.js
mapproxy/mapproxy.yaml

Simplify/Cleanup `mapproxy` configuration file

---

uwsgi/mapproxy.ini
uwsgi/mapproxy.py
uwsgi/skylines.py

Simplify WSGI wrapper scripts

---

systemd/caddy.service
systemd/celery.service
systemd/mapproxy.service
systemd/skylines.service
systemd/tracking.service

This makes the services easier to distinguish when using `journalctl` 🎉

systemd: Add `SyslogIdentifier` directives

---

Caddyfile

no need to a log file, `journald` will take care of it :)

Caddy: Log to stdout

---

Pipfile
Pipfile.lock

These are already brought in by other dependencies

Pipfile: Remove unnecessary transient dependencies

---

Caddyfile
ember/public/maintenance.html

This page can be enabled temporarily when performing maintenance work on the live server

Add maintenance page

---

fabfile.py

Update Fabric configuration

---

Pipfile
Pipfile.lock
skylines/app.py
skylines/sentry.py
skylines/tracking/server.py

Replace `raven` with `sentry-sdk`

---

ember/app/components/aircraft-model-select.js
ember/app/components/base-barogram.js
ember/app/components/base-map.js
ember/app/components/circling-performance-table.js
ember/app/components/fix-table-row.js
ember/app/components/fix-table.js
ember/app/components/flight-barogram.js
ember/app/components/flight-details-table.js
ember/app/components/flight-list-row.js
ember/app/components/nav-bar-menu-right.js
ember/app/components/pin-button.js
ember/app/components/pin-star.js
ember/app/components/settings-panels/tracking.js
ember/app/components/validated-block.js
ember/app/components/wingman-row.js
ember/app/controllers/index.js
ember/app/services/map-settings.js
ember/package.json
ember/yarn.lock

These will play nicer with using decorators in native ES6 classes.
This should unblock #1531
Closes #1520

Replace `ember-awesome-macros` with regular `computed()` properties

---

ember/app/components/recover-step1-form.js
ember/app/templates/components/recover-step1-form.hbs
skylines/api/views/users.py

... to make it easier for myself to answer such support requests 😩

users/recover: Return recovery URL when admin users request it

---

skylines/api/views/users.py

Fix email recovery issues

---

Pipfile
Pipfile.lock
skylines/app.py

... and enable more integrations 🎉

Update Sentry Python SDK 

---

ember/app/templates/components/flight-list.hbs

whoops, this got broken in #1697 🙈

flight-list: Fix `SortableTableHeader` invocation

---

ember/app/components/layer-switcher.js
ember/app/templates/components/layer-switcher.hbs
ember/package.json
ember/yarn.lock

One less component using jQuery and also less code overall 🎉

layer-switcher: Use `ember-click-outside` modifier to implement closing behavior

---

ember/app/components/flights-table-row.js

Remove unused `flights-table-row` component

---

ember/app/components/tracking-page.js
ember/app/templates/components/tracking-page.hbs

tracking-page: Replace `updateTimer` with ember-concurrency loop

---

.travis.yml

CI: Use Ubuntu Bionic Beaver

---

ember/app/templates/components/base-barogram.hbs
ember/app/templates/components/date-picker.hbs
ember/app/templates/components/datetime-picker.hbs
ember/app/templates/components/flight-page.hbs
ember/app/templates/components/tracking-page.hbs

This should unblock https://github.com/skylines-project/skylines/pull/1897

Use kebab-case for modifier invocations

---

ember/app/templates/components/base-map.hbs
ember/app/templates/components/flight-map.hbs
ember/app/templates/components/takeoffs-map.hbs

Use kebab-case for `set-map-target` modifier invocations

---

ember/yarn.lock

to make it compatible with Node 12

Update nested `fsevents` dependency

---

ember/app/templates/application.hbs
ember/app/templates/flight/index.hbs
ember/app/templates/tracking/details.hbs

instead of the deprecated `title` helper

Use `page-title` helper

---

ember/.eslintrc.js
ember/package.json
ember/yarn.lock

so that we can use decorators 😅

ESLint: Use `babel-eslint` parser

---

ember/app/components/flight-page.js
ember/app/components/progress-bar.hbs
ember/app/components/progress-bar.js
ember/app/routes/application.js
ember/app/routes/flights/-base.js
ember/app/routes/notifications.js
ember/app/routes/ranking/airports.js
ember/app/routes/ranking/clubs.js
ember/app/routes/ranking/pilots.js
ember/app/routes/search.js
ember/app/routes/timeline.js
ember/app/services/progress.js
ember/app/styles/app.scss
ember/app/styles/components/progress-bar.scss
ember/app/templates/application.hbs
ember/bower.json
ember/config/environment.js
ember/ember-cli-build.js
ember/package.json
ember/yarn.lock

similar to https://github.com/rust-lang/crates.io/pull/2571

Replace unmaintained `ember-cli-pace` with custom `progress` service

---

ember/app/index.html
ember/app/routes/application.js

similar to https://github.com/Turbo87/ogn-web-viewer

Implement initial loading spinner

---

ember/testem.js

see https://github.com/ember-cli/ember-new-output/blob/v3.19.0/testem.js

Update `testem.js` file

---

ember/app/components/fix-table-row.js
ember/app/components/fix-table.js
ember/app/components/flight-phase-row.js
ember/app/components/tracking-page.js
ember/app/components/wingman-row.js
ember/app/components/wingman-table.js
ember/app/services/units.js
ember/app/utils/fix-calc.js
ember/app/utils/fix.js

Convert a few files to use ES6 classes

---

ember/package.json
ember/yarn.lock

Remove obsolete `ember-cli-shims` dependency

---

ember/app/templates/components/flight-details-table.hbs
ember/app/templates/components/settings-panels/delete-account.hbs

see https://github.com/kaliber5/ember-bootstrap-codemods/blob/master/transforms/deprecated-attribute-arguments/README.md

BsButton: Fix `@disabled` deprecation warning

---

ember/app/components/cesium-button.js
ember/app/components/cesium-plane-models.js
ember/app/components/circling-performance-row.js
ember/app/components/comments-list.js
ember/app/components/contest-layer-feature.js
ember/app/components/sortable-table-header.js
ember/app/templates/components/cesium-button.hbs
ember/app/templates/components/cesium-plane-models.hbs
ember/app/templates/components/circling-performance-row.hbs
ember/app/templates/components/comments-list.hbs
ember/app/templates/components/flight-list.hbs
ember/app/templates/components/sortable-table-header.hbs

ES6 classes, Glimmer components, etc.

Modernize a few components

---

ember/app/helpers/is-undefined.js
ember/app/templates/components/fix-table-row.hbs
ember/app/templates/components/flight-leg-row.hbs
ember/app/templates/components/tracking-table-row.hbs

No need for this extra helper 🤷

Replace `is-undefined` helper with `eq`

---

ember/app/index.html

This is conflicting with `LinkTo` setting `loading` on links that are loading

Remove global `loading` CSS class

---

ember/app/services/intl.js
ember/tests/index.html

looks like I forgot a few things in #1965 ... 🙈

services/intl: Removing remaining unused polyfill data loading code

---

ember/app/components/comments-list.js

CommentsList: Fix "this.get is not a function" issue

---

ember/app/components/base-barogram.hbs
ember/app/components/base-barogram.js
ember/app/components/flight-barogram.js
ember/app/components/flight-page.hbs
ember/app/components/tracking-page.hbs

with a bunch of computed properties and a `did-update` modifier 💪

FlightBarogram: Replace `flights` observer

---

ember/app/components/validated-input.hbs

ValidatedInput: Pass attributes to `ValidatedBlock` component

---

ember/app/components/flight-barogram.js

without this the elevation display does not work 😅

FlightBarogram: Fix `selectedFlight` property

---

skylines/model/elevation.py

Resolves https://github.com/skylines-project/skylines/issues/612

model/elevation: Fix `MultipleResultsFound` issue

---

ember/bower.json
ember/ember-cli-build.js
ember/package.json
ember/yarn.lock

Import `sidebar-v2` from npm instead of bower

---

ember/bower.json
ember/ember-cli-build.js

This reverts commit 6609fd422057cc05a5ee4aec7caeda5b14afe8ea.
Resolves #2000

Revert "Use jQuery from `@ember/jquery`"

---

ember/package.json
ember/yarn.lock

see https://github.com/simplabs/qunit-console-grouper/

Add `qunit-console-grouper` dev dependency

---

ember/config/environment.js

Disable `ember-cli-mirage` in dev mode

---

ember/app/components/plane-label-overlay.hbs
ember/app/components/plane-label-overlay.js
ember/app/styles/_map.scss

PlaneLabelOverlay: Convert to Glimmer component

---

ember/app/components/upload-flight-form.hbs
ember/app/components/upload-flight-form.js

Adjust `UploadFlightForm` component

---

ember/app/services/map-settings.js

Simplify `map-settings` service

---

ember/app/components/comments-list.hbs
ember/app/components/comments-list.js
ember/app/components/flight-page.hbs
ember/mirage/vcr/flights/87296.js
ember/tests/acceptance/comments-test.js

... and add new tests to prevent this from happening again

CommentsList: Fix broken `addCommentTask` implementation

---

ember/app/components/fullscreen-button.js
ember/ember-cli-build.js
ember/package.json
ember/yarn.lock

see https://github.com/sindresorhus/screenfull.js

Replace `BigScreen` with `screenfull`

---

ember/app/components/sidebar/tab.hbs
ember/app/components/sidebar/tab.module.scss

because these links don't point anywhere...

Sidebar::Tab: Convert links to buttons

---

ember/app/components/map-click-handler.hbs
ember/app/components/map-click-handler.js
ember/app/services/notifications.js
ember/app/styles/application.module.scss
ember/app/templates/application.hbs
ember/app/templates/flights.hbs
ember/config/environment.js
ember/package.json
ember/yarn.lock

MapClickHandler: Use `ember-cli-notifications` addon for response feedback

---

.github/workflows/ci.yml
ember/package.json
ember/yarn.lock

see https://github.com/salsify/ember-cli-dependency-lint

CI: Add `ember-cli-dependency-lint` check

---

ember/app/components/comments-list.hbs
ember/app/components/comments-list.js
ember/app/components/comments-list.module.scss
ember/tests/acceptance/comments-test.js
ember/translations/de.yaml
ember/translations/en.yaml

because the network is always flaky...

CommentList: Add error handling and loading spinner

---

ember/app/templates/flights.hbs

flights: Remove unintended alert message

---

ember/mirage/factories/user.js
ember/mirage/models/user.js
ember/mirage/serializers/application.js
ember/tests/acceptance/comments-test.js
ember/tests/test-helpers/auth.js

to make it easier to write authenticated frontend tests in the future

Extract `authenticateAs()` test helper function

---

ember/package.json
ember/yarn.lock

see https://github.com/kaliber5/ember-cli-bundle-analyzer

Add `ember-cli-bundle-analyzer` addon

---

ember/app/authenticators/oauth2.js
ember/app/controllers/statistics.js
ember/app/routes/application.js
ember/app/services/account.js
ember/app/templates/statistics.hbs
ember/tests/acceptance/settings/delete-account-test.js
ember/tests/test-helpers/auth.js

This should hopefully fix the issue where after a certain time (most likely OAuth token timeout) the app forgets the user name.

 authenticators/oauth2: Remove session data mutation

---

ember/app/utils/fix-calc.js
ember/app/utils/raf.js

This sets us up for having adjustable playback speeds in the future :)

Simplify and improve playback code

---

ember/app/components/fullscreen-button.js
ember/translations/de.yaml
ember/translations/en.yaml

FullscreenButton: Show warning if fullscreen mode is not available

---

ember/app/components/fix-table-row.hbs
ember/app/utils/fix.js

using `-` makes the properties awkward to work with...

utils/fix: Rename `alt-msl/gnd` variables

---

.github/workflows/ci.yml
Caddyfile
ember/config/deploy.js

This PR is introducing a deploy job to our GitHub Actions CI setup, that will automatically deploy the frontend part of each commit on the `master` branch to our live server.

CI: Deploy frontend code automatically

---

.github/workflows/ci.yml

Forgot that in #2056 apparently 🙈

CI: Add missing `SENTRY_AUTH_TOKEN` env var

---

.github/workflows/ci.yml

see https://github.com/bobheadxi/deployments

CI: Integrate with GitHub deployments API

---

.github/workflows/ci.yml
ember/package.json

see https://github.com/volta-cli/action

Use `volta` to install and pin Node version

---

ember/app/components/timeline-events/club-join.hbs
ember/app/components/timeline-events/flight-comment.hbs
ember/app/components/timeline-events/flight-upload.hbs
ember/app/components/timeline-events/follower.hbs
ember/app/components/timeline-events/new-user.hbs
ember/app/components/timeline-events/ui.hbs
ember/app/components/timeline-events/ui.module.scss
ember/app/components/timeline.hbs
ember/app/components/timeline.module.scss
ember/app/styles/_events.scss
ember/app/styles/app.scss
ember/app/styles/notifications.module.scss
ember/app/styles/timeline.module.scss
ember/app/templates/notifications.hbs
ember/app/templates/timeline.hbs
ember/tests/components/timeline-events/club-join-test.js
ember/tests/components/timeline-events/flight-comment-test.js
ember/tests/components/timeline-events/flight-upload-test.js
ember/tests/components/timeline-events/follower-test.js
ember/tests/components/timeline-events/new-user-test.js

... and slightly tweak the styling to look better ✨

Reimplement `Timeline` components using CSS grid and CSS modules

---

ember/mirage/config.js
ember/mirage/factories/mirage-session.js
ember/mirage/models/mirage-session.js
ember/mirage/route-handlers/notifications.js
ember/mirage/route-handlers/settings.js
ember/mirage/route-handlers/users.js
ember/mirage/serializers/application.js
ember/mirage/serializers/user.js
ember/mirage/utils/session.js
ember/package.json
ember/tests/mirage/settings/get-test.js
ember/tests/mirage/user/get-test.js
ember/tests/test-helper.js
ember/tests/test-helpers/auth.js
ember/tests/test-helpers/match-json.js
ember/yarn.lock

Improve Mirage setup

---

ember/app/components/base-barogram.js
ember/app/components/contest-layer-feature.js
ember/app/utils/contest.js
ember/app/utils/flight-from-data.js

There is no need for this to be an `EmberObject` :)

Simplify `Contest` class

---

ember/app/components/base-barogram.hbs
ember/app/components/base-barogram.js
ember/app/components/flight-barogram.js
ember/app/components/flight-page.hbs
ember/app/components/flight-page.module.scss
ember/app/components/tracking-page.hbs
ember/app/components/tracking-page.module.scss
ember/app/components/upload-barogram.js
ember/app/components/upload-result-form.hbs
ember/app/components/upload-result-form.module.scss

This slightly simplifies the implementation by moving more imperative code to derived state.

Improve barogram components

---

ember/app/components/nav-bar-menu-right.hbs
ember/app/components/season-dropdown.hbs
ember/app/templates/ranking.hbs
ember/app/templates/statistics.hbs

These are causing issues with #2106

Fix `ember-bootstrap` deprecations

---

ember/tests/acceptance/comments-test.js
ember/tests/acceptance/flight-page-test.js
ember/tests/acceptance/index-test.js
ember/tests/acceptance/login-test.js
ember/tests/acceptance/page-not-found-test.js
ember/tests/acceptance/settings/delete-account-test.js
ember/tests/acceptance/upload-test.js
ember/tests/components/flight-list-nav-test.js
ember/tests/components/timeline-events/club-join-test.js
ember/tests/components/timeline-events/flight-comment-test.js
ember/tests/components/timeline-events/flight-upload-test.js
ember/tests/components/timeline-events/follower-test.js
ember/tests/components/timeline-events/new-user-test.js
ember/tests/helpers/format-altitude-test.js
ember/tests/helpers/format-distance-test.js
ember/tests/helpers/format-lift-test.js
ember/tests/helpers/format-speed-test.js
ember/tests/mirage/clubs/get-test.js
ember/tests/mirage/settings/get-test.js
ember/tests/mirage/user/get-test.js
ember/tests/services/map-settings-test.js
ember/tests/services/units-test.js
ember/tests/test-helpers/index.js

see http://emberjs.github.io/rfcs/0637-customizable-test-setups.html

Extract custom test setup functions

---

ember/app/components/fix-table-row.hbs
ember/app/components/fix-table-row.js

Resolves https://github.com/skylines-project/skylines/issues/2135

FixTableRow: Fix broken `onRemove()` call

---

ember/app/components/upload-result-form.hbs

see https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/time#Using_the_step_attribute

UploadResultForm: Use `step` attribute to force seconds input

---

airspace/airspace_list.txt

updated reference line 26 to fix us airspace file to current soaring web location

Update airspace_list.txt to fix link to us airspace

---

ember/public/_redirects

to hopefully make the API requests work :)

Netlify: Add `_redirects` file

---

docker-compose.yml
docker/docker-entrypoint-initdb.d/create-databases.sql

This should resolve https://github.com/skylines-project/skylines/pull/2314#issuecomment-751353811
more information is available at https://registry.hub.docker.com/_/postgres/ in the "Initialization scripts" section
/cc @vicb

Docker: Use `docker-entrypoint-initdb.d` to create necessary databases

---

.devcontainer/devcontainer.json
.devcontainer/docker-compose.yml
INSTALL.docker.md
INSTALL.md

Delete the outdated Vagrant config.
fixes #2311

Add information about Docker setup.

---

.github/renovate.json

This should hopefully unblock https://github.com/skylines-project/skylines/pull/2313

renovate: Adjust `postUpdateOptions` to use `yarnDedupeFewer`

---

ember/tests/acceptance/upload-test.js

... to make sure that we're actually sending what we're expecting to receive :)

tests/upload: Add request payload checks

---

ember/mirage/route-handlers/settings.js
ember/tests/mirage/settings/post-test.js

This will be needed for an upcoming feature

mirage: Add basic `POST /api/settings` route handler

---

.github/workflows/ci.yml
skylines/api/oauth.py
skylines/lib/igc.py

Update `black` to v20.8b1

---

skylines/api/views/upload.py
tests/api/views/flights/upload_test.py

Yet another bug in the flight upload code... 🤦‍♂️

api.views.upload: Fail if `pilot_id` is unknown

---

ember/app/components/upload-flight-form.hbs
ember/app/components/upload-flight-form.js
ember/app/components/upload-flight-form.module.scss
ember/app/components/weglide/user-id-field.hbs
ember/app/components/weglide/user-id-field.js
ember/tests/acceptance/upload-test.js
ember/tests/components/weglide/user-id-field-test.js
ember/translations/de.yaml
ember/translations/en.yaml

This is still a bit annoying because it does not remember the values for the next upload, but we will retrofit that functionality later.
see #2339

UploadFlightForm: Add basic "Upload to WeGlide" checkbox

---

ember/app/components/weglide/user-id-field.hbs
ember/translations/de.yaml
ember/translations/en.yaml

Makes it a little easier to figure out what WeGlide is, if you don't know it... 😅

WeGlide::UserId: Add link to the help text

---

skylines/weglide.py

weglide: Fix sentry log level

---

skylines/api/views/upload.py

... otherwise this can result in race conditions 🤦‍♂️

api.upload: Schedule `upload_to_weglide` tasks after DB transaction is committed

---

skylines/app.py

see https://docs.sentry.io/platforms/python/guides/flask/performance/

Sentry: Enable performance sampling

---

docker-compose.yml

Improve Docker setup

---

Dockerfile

see https://github.com/pypa/pipenv/issues/4476 🙄

Docker: Upgrade `virtualenv` before installing `pipenv`

---

Pipfile
Pipfile.lock
skylines/api/oauth.py

... and add user ID to events.
see https://docs.sentry.io/platforms/python/enriching-events/identify-user/

Update Sentry SDK 

---

Pipfile
Pipfile.lock

see https://github.com/pallets/flask/blob/master/CHANGES.rst#version-112

Update flask to v1.1.2

---

ember/app/routes/application.js
ember/app/routes/flight-upload.js
ember/app/routes/login.js
ember/app/routes/notifications.js
ember/app/routes/settings.js

see https://github.com/simplabs/ember-simple-auth/pull/2198

Fix ember-simple-auth deprecation warnings

---

ember/config/environment.js
ember/tests/components/weglide/user-id-field-test.js

looks like this is no longer in beta :D

weglide: Adjust `web` URL

---

.github/workflows/ci.yml

Reverts skylines-project/skylines#2417
because it's still broken... 😭

Revert "Update bobheadxi/deployments action to v0.5.1"

---

skylines/model/user.py

Resolves https://github.com/skylines-project/skylines/issues/881

model/user: Explicitly delete follower connections before deleting a user
