skylines-project/skylines

Vagrantfile

The packages `freetype6-dev` and `libpng-dev` resolve missing build dependencies of py-xcsoar.
Probably these dependencies were added between py-xcsoar version 0.4 and 0.5[1]
at " 10df972c60308f22cfc9076ffe831754e535f5c5:require xcsoar==0.5".
[1]: aka xcsoar/xcsoar@36ec48d44bea6148c02cac74487b89d8a2bd35f9 and 6.8.2

Vagrant: Add missing xcsoar build dependencies.

---

ember/bower.json
ember/package.json

This PR updates Ember, Ember CLI and a few other front-end dependencies. It also removes three unused dependencies from the `package.json` file.

Update Ember and dependencies

---

ember/app/services/raven.js
ember/bower.json
ember/config/environment.js
ember/package.json
skylines/frontend/templates/base.jinja
skylines/frontend/views/__init__.py

aaaaand we're switching the error reporting again... after a few tests it seems that sentry is much better suited than trackjs, especially since they also support flask, which means we can use it for both frontend *and* backend. I've contacted them and we will very likely receive a sponsored account there too.

Sentry error reporting

---

skylines/frontend/views/flight.py
tests/frontend/views/flight_test.py

Improvements when changing pilot:
- check, if the current user is in the same club as the pilot
- set pilot_name explicit to none, if pilot_id is given (for better traceability)
- add flight_test to test pilot changing

Fix server-side pilot/copilot permission check on flight update

---

ember/app/components/flight-page.js
ember/app/components/phase-highlight-composer.js
ember/app/components/share-button.js
ember/app/components/takeoffs-map.js
ember/app/components/tracking-page.js
ember/app/components/user-page.js
ember/app/services/cesium-loader.js
ember/app/services/pinned-flights.js
ember/app/templates/components/flight-map.hbs
ember/app/templates/components/flight-page.hbs
ember/app/templates/components/tracking-page.hbs

The `flightMap` global still remains, but this PR at least gets rid of all the others... 🎉

Eliminate global variables

---

ember/app/templates/settings/club.hbs

This makes sure we don't try to set `account.club.id` when `account.club` isn't set.
Resolves #509

templates/settings/club: Use "readonly" helper

---

ember/app/components/flight-details-table.js

Display flight's values, not IGC file's values at flight details table. Use the IGC file's values only for initializing the flight on upload.
Fixes #511

Use only flight's values for details table

---

ember/tests/integration/components/timeline-events/flight-comment-test.js
ember/tests/integration/components/timeline-events/flight-upload-test.js

This fixes the ESLint "no-useless-escape" errors, which occur since the last ESLint update.

Fix ESLint "no-useless-escape" errors

---

ember/app/router.js
ember/app/routes/tracking/map-redirect.js

Redirect the old /tracking/:user_ids/map route to /tracking/:user_ids, fixes #512

tracking: redirect old route with /map suffix

---

ember/app/controllers/application.js
ember/app/routes/application.js
ember/app/templates/application.hbs
ember/app/templates/components/nav-bar-menu-right.hbs
ember/app/templates/components/nav-bar.hbs

Previously the link transitioned back to the `flight-upload` route, but without resetting the controller. This meant that after uploading a flight there was no way to get back to the flight upload form without a page refresh, because you're always being directed to the upload results page.

Go to flight upload page when flight upload navbar link is clicked

---

ember/app/routes/tracking/info.js

The tracking info page previously suggested to login to view the live tracking key while already being logged in.

Fix tracking info page

---

ember/app/router.js
ember/app/routes/flight/map-redirect.js

This redirects the old /flights/<ids>/map route, fixes #554

flights: redirect old route with /map suffix

---

Vagrantfile

Since our Ember.js frontend can be built on any platform we don't have to build it *inside* of the VM
Resolves the other part of #563
/cc @pyrog

Vagrant: Remove frontend build instructions from startup script

---

Vagrantfile

Create "empty" directories used by the backend. (Cf. [Git FAQ](https://git.wiki.kernel.org/index.php/GitFaq#Can_I_add_empty_directories.3F))
Resolves #570

Add missing /htdocs folders

---

Vagrantfile

This allows us to access the DB from outside the VM via SSH tunneling

Vagrant: Set "postgres" DB user password for Vagrant dev machine

---

ember/.gitignore
ember/.travis.yml
ember/README.md
ember/bower.json
ember/package.json

This is mostly just following https://github.com/ember-cli/ember-new-output/compare/v2.9.1...v2.10.0 and brings us back onto a stable Ember.js release including the new Glimmer rendering engine.

Update Ember to v2.10.0

---

ember/app/components/plane-icons-composer.js
ember/app/utils/flight-from-data.js
ember/app/utils/flight.js
skylines/api/views/flights.py
skylines/lib/dbutil.py

This PR implements the server and client code to switch aircraft symbols on the map depending on the type of aircraft assigned to the flight.
Resolves #545 
Resolves #546
Closes #558
Thanks @pyrog for working on this! I don't know what I did wrong in https://github.com/skylines-project/skylines/pull/558#issuecomment-263116862, but when I tried it again it suddenly worked. I've updated your commits to the current state of `master` and adjusted a few small things.

Show different symbols on map depending on aircraft type

---

ember/app/templates/components/nav-bar-link.hbs
ember/app/templates/components/nav-bar-menu-right.hbs

works around https://github.com/alexspeller/ember-cli-active-link-wrapper/issues/25

Remove "title" properties from "link-to" components

---

.travis.yml
ember/.travis.yml
ember/app/routes/application.js

Otherwise `testem` is no using the `phantomjs` version we installed, but using the global one instead which is v1.9 by default on Travis.

CI: Install "phantomjs-prebuilt" globally

---

ember/app/components/nav-bar-menu-right.js
ember/app/routes/application.js
ember/app/services/intl.js
ember/config/ember-intl.js
ember/tests/acceptance/page-not-found-test.js
ember/tests/integration/components/flight-list-nav-test.js
ember/tests/integration/components/timeline-events/club-join-test.js
ember/tests/integration/components/timeline-events/flight-comment-test.js
ember/tests/integration/components/timeline-events/flight-upload-test.js
ember/tests/integration/components/timeline-events/follower-test.js
ember/tests/integration/components/timeline-events/new-user-test.js
ember/tests/unit/helpers/initials-test.js
ember/tests/unit/utils/add-days-test.js
ember/tests/unit/utils/parse-query-string-test.js

see https://github.com/jasonmit/ember-intl/blob/master/docs/asynchronously-loading-translations.md
this removes 200KB from our `app.js` file while adding one additional AJAX request for the requested translation. not sure yet what is worse...

Ember: Load translations async

---

ember/app/components/base-map.js
ember/app/components/share-button.js
ember/app/templates/club/index.hbs
ember/app/templates/components/search-result-row.hbs
ember/app/templates/index.hbs
ember/app/templates/tracking/info.hbs

This adds rel="noopener" to all external opened links with target=_"blank", fixes #625
see [https://developers.google.com/web/tools/lighthouse/audits/noopener](https://developers.google.com/web/tools/lighthouse/audits/noopener)

add "noopener" to all external links

---

ember/package.json
ember/yarn.lock

... to fix sourcemaps decoding issues on Sentry
see https://github.com/ef4/broccoli-uglify-sourcemap/pull/41

Use forked "broccoli-uglify-sourcemap" dependency

---

ember/.gitignore
ember/README.md
ember/app/index.html
ember/package.json
ember/yarn.lock

This does *not* include the change to use headless Chrome instead of PhantomJS for frontend testing

Update "ember-cli" to v2.15.0-beta.2

---

ember/app/components/flight-page.js
ember/app/components/tracking-page.js
ember/app/styles/_bootstrap-theme-skylines.scss
ember/app/styles/_ol3-sidebar.scss
ember/app/templates/components/flight-page.hbs
ember/app/templates/components/tracking-page.hbs

- The main menu is no longer hiding behind the sidebar
- The sidebar height is calculated properly on small devices
- The sidebar is collapsed by default on small screens or when tracking only a single pilot

Serveral styling fixes for the flight details page

---

.travis.yml

... and postgresql 9.5 with PostGIS 2.3
This should hopefully fix the currently failing CI builds

CI: Use "trusty" dist

---

ember/testem.js

This should fix the CI builds that broke due to https://github.com/travis-ci/travis-ci/issues/8836

testem: Use `--no-sandbox` on TravisCI

---

ember/package.json
ember/yarn.lock

This reverts commit b10519b9a67efbce0dbfc8c2fa66949d479c17bf. 
Main issue seems to be https://github.com/simplabs/ember-cookies/issues/145

Revert "Update `ember-cookies` to 0.1.2"

---

ember/app/components/base-map.js
ember/app/components/layer-switcher.js
ember/app/services/map-settings.js
ember/tests/unit/services/map-settings-test.js

This PR introduces a `map-settings` service that is responsible for managing and persisting which layers a user has selected from the layer switcher.

Add `map-settings` service

---

setup.py

Somewhere between 1.0 and 1.1.6 apparently they added support for using that package on Python 3.4 itself too

Update `enum34` to v1.1.6

---

setup.py

v0.6.1 has prebuilt wheels and support for Python 3 🎉

Update `xcsoar` to v0.6.1

---

mapserver/airports/airports.map
mapserver/fonts/truetype.txt

Apparently this broke a while ago but due to our use of `mapproxy` we did not notice this before. This PR adjusts the MapServer configuration files to be compatible with MapServer 7, which we now use on the production server.

Fix MapServer configuration

---

mapserver/airspace/airspace_blacklist.txt
mapserver/airspace/airspace_list.txt

This pull request updates the airspace files to the most recent versions found on soaringweb.org.
This changeset encompasses:
Germany, Belgium, France, Netherlands, Switzerland, Spain, Poland, Norway, Denmark, Finland
most are updated to 2017
This pull request closes #639, closes #381, closes #435

update airspace files to more recent versions

---

ember/app/utils/flight-collection.js

The previous implementation was using private API that was removed/changed with Ember 3.0

utils/flight-collection: Fix array content observers

---

Pipfile
Pipfile.lock

This is necessary for the production server, although ultimately we should think about running the mapproxy in a different virtualenv.

Add `mapproxy` dependency

---

uwsgi/mapproxy.ini
uwsgi/mapserver.ini
uwsgi/skylines.ini

This will enable us to use a different application server like gunicorn in the future without reconfiguring nginx, as well as using e.g. [Caddy](https://github.com/mholt/caddy) instead of nginx

Use `http` protocol for `uwsgi`

---

supervisor/mapserver.conf

Unfortunately [mapscript](http://mapserver.org/de/mapscript/python.html) refuses to be installed in a normal way, and needs to be installed from the system-level package manager. This means it's not part of the usual virtualenv.
This PR changes the `supervisord` configuration to run the `mapserver` program outside of the virtualenv, so that it has access to the globally installed `mapscript` dependency.
I wish this was easier... 🤷‍♂️

supervisor/mapserver: Run outside of the virtualenv

---

ember/app/templates/components/comments-list.hbs

Use CSS3 property `word-wrap` to wrap long strings (e.g. long URLs),
use `table-layout` property to properly set the table width according
to the parent element.
Tested in Firefox 60.0.1 and Chromium 66.0.3359.181.
Fixes #257.
I'm not sure where to set these style properties (thus resorted to inline CSS).
Previous:
Fixed:

components/comments-list: Fix table width and word wrapping

---

PRIVACY.md

The line
`If you do create an account, you do not need to give us your email address.`
is wrong and contradictory to 
`If you want to create a standard account, we require only your name, an email
address and a password.`
So i ~~removed~~ changed it.

privacy policy: fix information regarding email address when creating an account

---

Pipfile

This allows us to use `pipenv run manage` instead of `pipenv run ./manage.py`

Pipfile: Add `manage` script

---

.travis.yml

Previously the CI jobs would be run once for the branch, and another time for the PR, which is wasting resources.
/cc @dependabot

CI: Prevent `dependabot` branches from building twice

---

tests/data/events.py

The octal prefix is no longer supported by Python 3 and wasn't even intended in the first place.

tests/events: Remove unintended octal literal prefixes

---

skylines/tracking/crc.py

tracking/crc: Explicitly pass bytestring to `crc16xmodem` function

---

tests/api/views/conftest.py

so that e.g. the `test_read_missing_user` test can run in isolation

tests/api/views: Set `autouse` for `db_session` fixture

---

.travis.yml

This PR adjusts the TravisCI configuration to also run the backend tests on Python 3.4, but since they currently do not pass it allows failures for now.

CI: Run on Python 3.4 too

---

skylines/api/oauth.py

Byte strings are not JSON serializable in Python 3

api/oauth: Ensure access tokens are JSON serializable

---

skylines/api/oauth.py

This should hopefully get rid of the current SQLAlchemy warnings in CI.

api/oauth: Convert `username` to unicode if necessary

---

skylines/api/views/i18n.py

api/i18n: Use list comprehension instead of `map/filter()`

---

skylines/model/geo.py

This should make the corresponding geo tests pass on Python 3

model/geo: Use list comprehension instead of `map()`

---

.travis.yml

Hopefully that helps...
related to https://github.com/pypa/pipenv/pull/2968

CI: Pin pipenv version to fix CI builds

---

Pipfile.lock

not sure how they got in there but they were making local development impossible :(

pipenv: Remove invalid extra markers from `Pipfile.lock`

---

skylines/lib/string.py
skylines/model/aircraft_model.py
skylines/model/airport.py
skylines/model/airspace.py
skylines/model/club.py
skylines/model/event.py
skylines/model/flight.py
skylines/model/flight_comment.py
skylines/model/igcfile.py
skylines/model/mountain_wave_project.py
skylines/model/notification.py
skylines/model/timezone.py
skylines/model/tracking.py
skylines/model/user.py
tests/model/test_user.py

`__repr__` is always supposed to return `str` ("bytes" in Python 2, "unicode" in Python 3)

Make `__repr__` implementations compatible with Python 3 

---

skylines/lib/types.py

This file handles Python 2/3 compat and is expected to have undefined names in the branches that don't run for the corresponding versions

lib/types: Ignore "undefined name" warnings

---

skylines/commands/import_/airspace.py

commands/import/airspace: Use `.decode()` instead of `unicode` cast

---

skylines/model/flight.py
tests/api/views/flights/read_test.py

because division works slightly different in Python 3...

model/flight: Ensure floats are used in division operation

---

skylines/api/views/notifications.py
skylines/api/views/statistics.py
skylines/api/views/tracking.py
skylines/api/views/users.py

api/views: Use `.name` instead of `unicode()` conversion

---

Pipfile.lock

This was upgraded by mistake and dropped support for Python 3.4 which we are using on CI right now

Revert `webargs` to v3.0.2

---

Pipfile.lock

see https://github.com/pypa/pipenv/issues/3026

pipenv: Remove broken extra markers

---

Pipfile.lock

Reverts skylines-project/skylines#1243
For some strange reason this seems to break CI on the `master` branch... and it also bumped `redis` unintentionally

Revert "Bump cryptography from 2.4.1 to 2.4.2"

---

Pipfile
Pipfile.lock

... because Python devs don't understand semver that well 🙄
see https://github.com/lepture/flask-oauthlib/pull/388
Resolves https://github.com/skylines-project/skylines/issues/1398

Pin `requests-oauthlib`

---

Vagrantfile

... because right now `py-xcsoar` will complain about a missing `Python.h` file 😢

Vagrant: Fix `python-dev` instructions

---

.gitignore
INSTALL.mapserver.md
fabfile.py
mapproxy/mapproxy.yaml
uwsgi/mapproxy.ini

This will keep the cache in the `cache_data` folder right next to the config file in the top-level `mapproxy` folder. That means we no longer need to use a different file on the production server, which then means that relative paths in the `mapproxy.yaml` file will work properly again.

mapproxy: Remove explicit cache folder settings

---

Caddyfile

Previously the `index.html` file did not have an `Expires` header, which meant that it was cached locally in the browser for a while, which is certainly not what we want. This PR sets `expires: 0s` for all responses that don't have any other configuration set.

Caddy: Simplify `expires` configuration

---

Caddyfile
uwsgi/mapproxy.ini
uwsgi/skylines.ini

While supposedly not as efficient as UNIX sockets, TCP sockets make things a little easier to handle with regard to filesystem permissions

uwsgi: Serve on TCP sockets

---

Pipfile
Pipfile.lock

`redis@3` is apparently not compatible with our current Celery version 😢

Revert `redis` back to v2.10.6

---

ember/config/ember-intl.js
ember/package.json
ember/yarn.lock

Thanks to https://github.com/ember-intl/ember-intl/pull/700 we can finally upgrade `ember-intl` again.

Update `ember-intl` to v4.0.0-beta.8

---

Caddyfile

`www02.skylines.aero` is the domain of the new server and will redirect to `skylines.aero` as the main domain now.
`tracking.skylines.aero` is used by XCSoar v7 as the live tracking endpoint. just in case someone tries to access it via HTTP we will redirect them to the right browser URL.

Caddy: Add `www02` and `tracking` redirections

---

Caddyfile
systemd/mapproxy.service
systemd/skylines.service

Apparently `journald` is not meant for "high-frequency logging" like webserver access logs. This PR changes the logging strategy back to files or not logging access logs at all.
/cc @lordfolken

Remove `journald` logging

---

ember/app/routes/search.js

This fixes a regression introduced by dbf6802 since accessing
`queryParams` on the `Transition` have been deprecated in
Ember v3.x and removed in v3.10.
Fixes #1641.

routes/search: Use params.text as searchText

---

ember/package.json
ember/yarn.lock

It has been replaced by `@ember/test-helpers`, which is brought in by `ember-qunit`.

Remove obsolete `ember-native-dom-helpers` dependency

---

ember/package.json
ember/yarn.lock

`ember-cli-htmlbars` is all we need these days 🎉

Remove obsolete `ember-cli-htmlbars-inline-precompile` dependency

---

ember/app/components/cesium-button.js
ember/app/components/fullscreen-button.js
ember/app/components/playback-button.js

This fixes the annoying "Fullscreen button click causes 3D mode to activate" bug on touch devices 🙈

*-button: Fix tap behavior on touch devices

---

systemd/celery.service

Our celery service currently does not seem to restart itself when it quits for unknown reasons. This change does not fix the unknown issue that causes celery to crash, but should hopefully at least cause it to restart itself whenever it quits on its own.
This should avoid issues like https://github.com/skylines-project/skylines/issues/1529 in the future.

systemd/celery: Always restart `celery` service

---

ember/app/components/base-barogram.js
ember/app/components/date-picker.js
ember/app/components/datetime-picker.js
ember/app/components/flight-page.js
ember/app/components/tracking-page.js
ember/app/components/upload-flight-form.js

This is getting rid of all `this.$()` calls in the app to fix the corresponding deprecation warnings.

Replace `this.$()` calls

---

ember/config/optional-features.json
ember/package.json
ember/yarn.lock

We no longer use `this.$()` and jQuery itself will be provided by `@ember/jquery` now.

Disable jQuery integration

---

ember/lib/freestyle/app/components/usage/datetime-picker.js
ember/lib/freestyle/app/templates/components/usage/datetime-picker.hbs

because it needs to be testable outside of the flight upload flow

freestyle: Add `datetime-picker` usage example

---

skylines/lib/igc.py
tests/lib/test_igc.py

Looks like the Naviter Oudie is producing such headers now and according to the IGC file spec they are valid 🤷‍♂️

igc: Allow `HFDTEDATE:` headers

---

Pipfile
Pipfile.lock

This will fix the missing support for long-form `HFDTE` headers in IGC files
Resolves https://github.com/skylines-project/skylines/issues/1878

Update `xcsoar` dependency to v0.7.0

---

ember/app/templates/components/flight-page.hbs
ember/app/templates/components/tracking-page.hbs

This is a bad workaround, but it unblocks the update to Ember 3.16/3.19.

Flight|TrackingPage: Unwrap `ArrayProxy` before handing `flights` to `FlightBarogram`

---

ember/app/helpers/format-altitude.js
ember/app/helpers/format-distance.js
ember/app/helpers/format-lift.js
ember/app/helpers/format-speed.js
ember/tests/helpers/format-altitude-test.js
ember/tests/helpers/format-distance-test.js
ember/tests/helpers/format-lift-test.js
ember/tests/helpers/format-speed-test.js
ember/tests/services/units-test.js

This PR adds tests for the `units` service and the corresponding `format-distance|altitude|lift|speed` helpers, it removes the obsolete `observer` from these helpers and ensures that they invalidate their values when the locale changes.

Fix format unit helper invalidation when locale changes

---

ember/app/services/intl.js

ember-intl does this natively now 💪

services/intl: Remove obsolete `lang` attribute assignment

---

ember/bower.json
ember/ember-cli-build.js

There is no need for us to use this old and outdated version of jQuery anymore

Use jQuery from `@ember/jquery`

---

ember/ember-cli-build.js

Since we don't use Glyphicons anywhere anymore

Disable Bootstrap font bundling

---

ember/app/services/notification-counter.js

This should solve a few of the "Ajax authorization failed" errors.

services/notification-counter: Ignore network errors

---

ember/app/components/map-click-handler.js

This should hopefully work around https://github.com/skylines-project/skylines/issues/2068 for now

map-click-handler: Use `setPosition()` after adding overlay to the map

---

.github/renovate.json

Instead of disabling all managers except `npm`

renovate: Disable `python` language

---

ember/config/dependency-lint.js

We run lint on CI, there is no need to slow down the build process by generating tests

dependency-lint: Disable test generation

---

ember/tests/acceptance/flight-page-test.js
ember/tests/acceptance/upload-test.js
ember/tests/test-helpers/cookies.js

... to make sure the local `SkyLines_pinnedFlights` cookie is not messing with the tests.

Implement `cookie` service mocking for tests

---

.dockerignore
.github/workflows/ci.yml
Dockerfile
config/default.py
docker-compose.yml

This Docker-based setup will hopefully make it a bit more straight-forward in the future to have the same thing running locally as in CI.
Please note that this is currently primarily targeted at working for CI. For local development a few adjustments are still needed, like for example using a different database name.

Use `docker-compose` setup to fix CI

---

tests/api/views/tracking/__init__.py
tests/api/views/tracking/latest_test.py
tests/api/views/tracking/live_multiple_test.py
tests/api/views/tracking/live_test.py
tests/data/live_fix.py

Hey @Turbo87,
in order to prepare for the changes related to https://github.com/skylines-project/skylines/issues/2277 I have first added unit tests to test the current behavior.
Could you please review ?
Thanks

Add tests for the live tracking API endpoints

---

skylines/commands/tracking/generate_through_daemon.py

This will allow us to use `./manage.py tracking generate_through_daemon --host tracking 42` once there is a `tracking` Docker service.

commands.tracking.generate_through_daemon: Add `--host/port` options

---

docker-compose.yml

This PR adds a `worker` service to the `docker-compose.yml` file, which runs our Celery-based task queue.

 Docker: Add `worker` service

---

skylines/commands/tracking/generate_through_daemon.py

This model instance does not appear to be used anywhere and is probably just a relict from copying the other `generate` command code.

commands.tracking.generate_through_daemon: Remove unused `TrackingFix` instance

---

docker-compose.yml
skylines/commands/tracking/server.py

This PR adds another service to the docker-compose setup, which runs our Live Tracking server and exposes it on the UDP port 5597 on the host machine.
To generate test data through that server you can use:
```
docker-compose run api pipenv run ./manage.py tracking generate-through-daemon --host tracking 1
```

Docker: Add `tracking` service

---

ember/app/components/pilot-select.hbs
ember/app/components/upload-flight-form.hbs
ember/tests/acceptance/upload-test.js

During flight upload the pilot selection field was previously not disabled. This PR fixes the issue and adjusts the existing upload test to check for this too.

UploadFlightForm: Disable pilot selection while uploading

---

ember/app/components/fix-table.hbs

`this.onRemove` does not exist on the JS class, which was causing errors

FixTable: Fix `@onRemove` assignment

---

Pipfile
Pipfile.lock
migrations/versions/58325345d375_add_weglide_fields_to_igcfile.py
skylines/api/views/upload.py
skylines/model/igcfile.py
skylines/schemas/schemas.py
skylines/weglide.py
skylines/worker/tasks.py
tests/api/views/flights/upload_test.py
tests/schemas/schemas/test_flight_upload.py
tests/weglide/upload_test.py

This PR adds a `upload_to_weglide` worker task based on Celery, that receives an IGC file ID, a WeGlide user ID and a birthdate, and then calls the WeGlide API to upload the IGC file over there. This task is automatically queued up when upload API request contains the `weglideUserId` and `weglideBirthday` fields. The result of the API call is saved in the new `weglide_status` and `weglide_data` fields on the `IGCFile` model and will be serialized on the API in a follow-up PR.
This addresses the first part of #2339

Add `upload_to_weglide` worker task

---

skylines/schemas/schemas.py
tests/api/views/flights/read_test.py
tests/api/views/flights/upload_test.py

This PR implements part two of #2339 by exposing the two new IGC file fields on the API

IGCFile: Expose WeGlide fields on the API

---

ember/app/components/flight-details-table.js
ember/app/components/flight-page.hbs
ember/app/controllers/flight/index.js
ember/app/templates/flight/index.hbs

muuuuuch easier than having to pass `transitionTo` along everywhere 😅

FlightDetailsTable: Use `router` service to navigate

---

.github/workflows/ci.yml

Reverts skylines-project/skylines#2413
Looks like this breaks our continuous deployment pipeline 🤔

Revert "Update bobheadxi/deployments action to v0.5.0"

---

ember/app/templates/tracking/info.hbs
skylines/frontend/views/livetrack24.py

According to their new docs, the current referenced link is for a deprecated API.

docs(livetrack24): fix link to Livetrack24 tracking api
